### ISSUE TITLE
UI ninepatches issue

### ISSUE THREAD

**Issue by czyzby** [Quillraven/Dark-Matter#4]
Hey, I've noticed that there seems to be some kind of issue with the ninepatches in the UI. It adds extra transparent/black pixels around the corners, which looks like an unintended UI bug:

![image](https://user-images.githubusercontent.com/11707612/80707142-cc6e1180-8ae9-11ea-927e-ad80c50af441.png)

I suggest removing these gaps.

**Comment by czyzby** [comment]
I believe all you have to do is remove or paint over the black lines in the [frame.9.png](https://github.com/Quillraven/Dark-Matter/blob/master/raw/ui/frame.9.png) file.

**Comment by Quillraven** [comment]
hm okay didn't notice that. I create nine-patches with following website: http://romannurik.github.io/AndroidAssetStudio/nine-patches.html#&sourceDensity=320&name=example

this usually adds 4 black lines at the top,bottom,left and right edges which from my understanding get interpreted in a special way so that they are correctly treated as nine-patches.

Will check it on the weekend if I can reproduce your issue. If yes, maybe it is also related to add padding when they ninepatches get added to the textureatlas?

**Comment by czyzby** [comment]
I think Android ninepatches might be a bit different than LibGDX ninepatches. I'll submit a PR.

**Comment by czyzby** [comment]
See #5. You can try to rebuild the UI with the ninepatch I added and see if it looks better. I also included some comments around the UI assets that you might find useful.

**Comment by Quillraven** [comment]
@czyzby I am not able to see the issue :( I added two buttons for testing and cleared the screen with a red color to see borders more clearly but to me it looks just fine (refer to screenshot).

Can you tell me please, how to reproduce your case with the black borders?

![image](https://user-images.githubusercontent.com/93260/80795046-bc166f00-8b9b-11ea-9cde-1b37495ea5f8.png)

**Comment by czyzby** [comment]
I don't mean the black borders _around_ the buttons, I mean that the black lines near the corners look unintentional. This is what I believe would look better:

![image](https://user-images.githubusercontent.com/11707612/80798311-685c5380-8ba4-11ea-8247-a0c4fc05dbee.png)

**Comment by czyzby** [comment]
If the black lines near the corners were intentional, I think they're a bit too dark and look out of place - more like a visual bug than an intended effect. If you'd like to have clear outlines around the corners, you could try recoloring them to e.g. out of the darker blues in the palette.

**Comment by Quillraven** [comment]
aaaah now I know what you mean haha. Well, actually I only adjusted the [original graphics](https://cluly.itch.io/space-eaters) a little bit to use it as a button frame. The original one already had those black lines in it and I guess it should look like a metal pipe or something? :D

But now that you mention it and I see the difference with your graphic, it indeed looks weird.

**Comment by czyzby** [comment]
I think the way you render it stretches the pixels a bit, which worsens this effect. Anyway, if that's the look they were going for and you think it's fine, you can close the issue. I still think it looks smoother without the black lines or with less contrast:
![image](https://user-images.githubusercontent.com/11707612/80804504-a9a92f00-8bb5-11ea-965a-678ea49351eb.png)
(You could of course tweak the colors and possibly add some shading to the lines, but you get the idea.)

**Comment by Quillraven** [comment]
@czyzby I updated the graphics now (9e96aa62b227d15a7d4baccaa011abf61d7b2cb8) and I saw that ImageButtonStyle extends ButtonStyle and therefore you can set an up and imageUp graphic. Up is the frame graphic of the button and imageUp is the centered image of the frame like the sound icons. 
Due to that it was actually easier to optimize the imagebuttons. I just had to adjust the skin a little bit :)

What do you think? Is it better now?

![image](https://user-images.githubusercontent.com/93260/80909722-bc914000-8d2a-11ea-969a-88f44454cfae.png)

![image](https://user-images.githubusercontent.com/93260/80909726-c87d0200-8d2a-11ea-8d10-c030cf6d15cb.png)

![image](https://user-images.githubusercontent.com/93260/80909733-d3379700-8d2a-11ea-84c9-bd87ee231e34.png)

**Comment by czyzby** [comment]
Much better. I like how the corners stand out a little bit in some of the elements, although I wouldn't overuse this effect. I'm no UX/UI designer, but I'd consider saving this background only for elements that you can interact with (such as buttons). Currently there is no way to differentiate a label with a background from a button on first glance.

**Comment by Quillraven** [comment]
Made a second version now for labels without the edges and a little darker colors in general - what do you think?

The first two are just "labels" while the last one is a clickable button

![image](https://user-images.githubusercontent.com/93260/80912569-151e0880-8d3e-11ea-8492-b7ca80695803.png)

**Comment by czyzby** [comment]
Again, not a UX/UI designer, but I think it's OK to make the buttons stand out - especially if it's consistent throughout the application. Might as well do this with the corners. Looks fine for me.

**Comment by Quillraven** [comment]
thanks for the input, as always  :)
